<?php
require_once __DIR__ . '/../includes/functions.php';
ensure_default_settings($pdo);
require_admin();
$allowedTabs = array('verification','stats','recruiters','couriers','city-rates','news','settings');
$tab = isset($_GET['tab']) ? $_GET['tab'] : 'verification';
if (!in_array($tab, $allowedTabs, true)) { $tab = 'verification'; }
$errors = array(); $message = '';
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    verify_csrf();
    $action = isset($_POST['action']) ? $_POST['action'] : '';
    try {
        if ($action === 'approve_courier') {
            $id = (int) $_POST['id'];
            $stmt = $pdo->prepare("UPDATE couriers SET status = 'active', rejection_reason = NULL WHERE id = ? AND deleted_at IS NULL");
            $stmt->execute(array($id)); $message = 'Курьер принят.'; $tab = 'verification';
        }
        if ($action === 'reject_courier') {
            $id = (int) $_POST['id']; $reason = trim(isset($_POST['rejection_reason']) ? $_POST['rejection_reason'] : '');
            if ($reason === '') { throw new RuntimeException('Укажите причину отклонения.'); }
            $stmt = $pdo->prepare('SELECT c.*, u.id AS recruiter_id FROM couriers c JOIN users u ON u.id = c.recruiter_id WHERE c.id = ? LIMIT 1');
            $stmt->execute(array($id)); $courier = $stmt->fetch(); if (!$courier) { throw new RuntimeException('Курьер не найден.'); }
            $stmt = $pdo->prepare("UPDATE couriers SET status = 'rejected', rejection_reason = ? WHERE id = ?");
            $stmt->execute(array($reason, $id));
            create_notification($pdo, $courier['recruiter_id'], 'Курьер отклонён', 'Курьер ' . $courier['first_name'] . ' ' . $courier['last_name'] . ' отклонён. Причина: ' . $reason);
            $message = 'Курьер отклонён, рекрутер уведомлён.'; $tab = 'verification';
        }
        if ($action === 'approve_withdrawal' || $action === 'reject_withdrawal') {
            $id = (int) $_POST['id']; $comment = trim(isset($_POST['admin_comment']) ? $_POST['admin_comment'] : ''); $status = $action === 'approve_withdrawal' ? 'approved' : 'rejected';
            $stmt = $pdo->prepare('UPDATE withdrawals SET status = ?, admin_comment = ?, processed_at = NOW() WHERE id = ? AND status = \'pending\'');
            $stmt->execute(array($status, $comment, $id)); $message = $status === 'approved' ? 'Выплата одобрена.' : 'Выплата отклонена.'; $tab = 'verification';
        }
        if ($action === 'save_recruiter') {
            $id = (int) $_POST['id']; $fullName = trim($_POST['full_name']); $email = strtolower(trim($_POST['email'])); $customReward = trim(isset($_POST['custom_reward']) ? $_POST['custom_reward'] : '');
            if ($fullName === '' || !filter_var($email, FILTER_VALIDATE_EMAIL)) { throw new RuntimeException('Проверьте имя и email.'); }
            $stmt = $pdo->prepare("UPDATE users SET full_name = ?, email = ? WHERE id = ? AND role = 'recruiter'"); $stmt->execute(array($fullName, $email, $id));
            if ($customReward === '') { $stmt = $pdo->prepare('DELETE FROM recruiter_overrides WHERE recruiter_id = ?'); $stmt->execute(array($id)); }
            else { $stmt = $pdo->prepare('INSERT INTO recruiter_overrides (recruiter_id, reward_per_order) VALUES (?, ?) ON DUPLICATE KEY UPDATE reward_per_order = VALUES(reward_per_order)'); $stmt->execute(array($id, (int) $customReward)); }
            $message = 'Рекрутер сохранён.'; $tab = 'recruiters';
        }
        if ($action === 'delete_recruiter') { $stmt = $pdo->prepare("DELETE FROM users WHERE id = ? AND role = 'recruiter'"); $stmt->execute(array((int) $_POST['id'])); $message = 'Рекрутер удалён.'; $tab = 'recruiters'; }
        if ($action === 'save_courier') {
            $id = (int) $_POST['id']; $orders = max(0, (int) $_POST['orders_count']); $status = $_POST['status']; if (!in_array($status, array('pending','active','rejected','paused','blocked'), true)) { $status = 'pending'; }
            $stmt = $pdo->prepare('UPDATE couriers SET first_name=?, last_name=?, city=?, delivery_type=?, phone=?, status=?, rejection_reason=?, orders_count=? WHERE id=?');
            $stmt->execute(array(trim($_POST['first_name']), trim($_POST['last_name']), trim($_POST['city']), $_POST['delivery_type'], trim($_POST['phone']), $status, trim($_POST['rejection_reason']), $orders, $id));
            $message = 'Курьер сохранён.'; $tab = 'couriers';
        }
        if ($action === 'delete_courier') { $stmt = $pdo->prepare('UPDATE couriers SET deleted_at = NOW() WHERE id = ?'); $stmt->execute(array((int) $_POST['id'])); $message = 'Курьер удалён.'; $tab = 'couriers'; }
        if ($action === 'save_setting') { $reward = (int) $_POST['reward_per_order']; if ($reward < 0) { throw new RuntimeException('Ставка не может быть отрицательной.'); } set_setting($pdo, 'reward_per_order', (string) $reward); set_setting($pdo, 'min_withdrawal', (string) max(0, (int) $_POST['min_withdrawal'])); $message = 'Настройки сохранены.'; $tab = 'settings'; }
        if ($action === 'save_city_rate') { $city = trim($_POST['city']); $rate = (int) $_POST['reward_per_order']; if ($city === '' || $rate < 0) { throw new RuntimeException('Проверьте город и ставку.'); } $stmt = $pdo->prepare('INSERT INTO city_rates (city, reward_per_order) VALUES (?, ?) ON DUPLICATE KEY UPDATE reward_per_order = VALUES(reward_per_order)'); $stmt->execute(array($city, $rate)); $message = 'Ставка города сохранена.'; $tab = 'city-rates'; }
        if ($action === 'delete_city_rate') { $stmt = $pdo->prepare('DELETE FROM city_rates WHERE id = ?'); $stmt->execute(array((int) $_POST['id'])); $message = 'Ставка удалена.'; $tab = 'city-rates'; }
        if ($action === 'post_news') { $title = trim($_POST['title']); $body = trim($_POST['body']); if ($title === '' || $body === '') { throw new RuntimeException('Заполните заголовок и текст новости.'); } $stmt = $pdo->prepare('INSERT INTO news (title, body) VALUES (?, ?)'); $stmt->execute(array($title, $body)); $recruiters = $pdo->query("SELECT id FROM users WHERE role = 'recruiter'")->fetchAll(); foreach ($recruiters as $r) { create_notification($pdo, $r['id'], $title, $body); } $message = 'Новость опубликована и отправлена рекрутерам.'; $tab = 'news'; }
    } catch (Throwable $exception) { $errors[] = $exception->getMessage(); }
}
$reward = (int) get_setting($pdo, 'reward_per_order', '30'); $minWithdrawal = (int) get_setting($pdo, 'min_withdrawal', '500');
$stats = array('recruiters'=>(int)$pdo->query("SELECT COUNT(*) FROM users WHERE role='recruiter'")->fetchColumn(), 'couriers'=>(int)$pdo->query('SELECT COUNT(*) FROM couriers WHERE deleted_at IS NULL')->fetchColumn(), 'orders'=>(int)$pdo->query("SELECT COALESCE(SUM(orders_count),0) FROM couriers WHERE status='active' AND deleted_at IS NULL")->fetchColumn(), 'paid'=>(float)$pdo->query("SELECT COALESCE(SUM(amount),0) FROM withdrawals WHERE status='approved'")->fetchColumn());
$recruiters = $pdo->query("SELECT u.*, ro.reward_per_order AS custom_reward FROM users u LEFT JOIN recruiter_overrides ro ON ro.recruiter_id = u.id WHERE u.role='recruiter' ORDER BY u.created_at DESC")->fetchAll();
$statusFilter = isset($_GET['status']) ? $_GET['status'] : '';
if ($statusFilter !== '' && in_array($statusFilter, array('pending','active','rejected','paused','blocked'), true)) { $stmt = $pdo->prepare('SELECT c.*, u.full_name AS recruiter_name FROM couriers c JOIN users u ON u.id=c.recruiter_id WHERE c.deleted_at IS NULL AND c.status=? ORDER BY c.registered_at DESC'); $stmt->execute(array($statusFilter)); $couriers = $stmt->fetchAll(); } else { $couriers = $pdo->query('SELECT c.*, u.full_name AS recruiter_name FROM couriers c JOIN users u ON u.id=c.recruiter_id WHERE c.deleted_at IS NULL ORDER BY c.registered_at DESC')->fetchAll(); }
$pendingCouriers = $pdo->query("SELECT c.*, u.full_name AS recruiter_name FROM couriers c JOIN users u ON u.id=c.recruiter_id WHERE c.status='pending' AND c.deleted_at IS NULL ORDER BY c.registered_at ASC")->fetchAll();
$pendingWithdrawals = $pdo->query("SELECT w.*, u.full_name AS recruiter_name FROM withdrawals w JOIN users u ON u.id=w.recruiter_id WHERE w.status='pending' ORDER BY w.created_at ASC")->fetchAll();
$cityRates = $pdo->query('SELECT * FROM city_rates ORDER BY city ASC')->fetchAll(); $news = $pdo->query('SELECT * FROM news ORDER BY created_at DESC LIMIT 20')->fetchAll();
$pageTitle='Админ-панель'; $bodyClass='app-layout'; $activePage=$tab; $pageHeading='Панель управления'; require __DIR__ . '/../includes/header.php'; require __DIR__ . '/../includes/admin-sidebar.php';
?>
<?php if ($message): ?><div class="alert alert-success"><?= e($message) ?></div><?php endif; ?><?php if ($errors): ?><div class="alert alert-error"><?= e(implode(' ', $errors)) ?></div><?php endif; ?>
<?php if ($tab === 'verification'): ?><section class="panel"><div class="panel-heading"><h2>Проверка курьеров</h2></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Курьер</th><th>Город</th><th>Тип</th><th>Рекрутер</th><th>Дата</th><th>Действия</th></tr></thead><tbody><?php foreach ($pendingCouriers as $c): ?><tr><td><?= e($c['first_name'].' '.$c['last_name']) ?></td><td><?= e($c['city']) ?></td><td><?= e(delivery_type_label($c['delivery_type'])) ?></td><td><?= e($c['recruiter_name']) ?></td><td><?= e(date('d.m.Y', strtotime($c['registered_at']))) ?></td><td class="actions-cell"><form method="post"><?= csrf_field() ?><input type="hidden" name="action" value="approve_courier"><input type="hidden" name="id" value="<?= (int)$c['id'] ?>"><button class="button small" type="submit">Принять</button></form><form method="post" data-require-reason="true"><?= csrf_field() ?><input type="hidden" name="action" value="reject_courier"><input type="hidden" name="id" value="<?= (int)$c['id'] ?>"><input type="hidden" name="rejection_reason"><button class="button small danger" type="submit">Отклонить</button></form></td></tr><?php endforeach; ?></tbody></table></div></section><section class="panel"><div class="panel-heading"><h2>Проверка выплат</h2></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Рекрутер</th><th>Сумма</th><th>Дата</th><th>Комментарий</th><th>Действия</th></tr></thead><tbody><?php foreach ($pendingWithdrawals as $w): ?><tr><td><?= e($w['recruiter_name']) ?></td><td><?= format_money($w['amount']) ?></td><td><?= e(date('d.m.Y', strtotime($w['created_at']))) ?></td><td><?= e($w['comment']) ?></td><td class="actions-cell"><form method="post"><?= csrf_field() ?><input type="hidden" name="action" value="approve_withdrawal"><input type="hidden" name="id" value="<?= (int)$w['id'] ?>"><button class="button small" type="submit">Одобрить</button></form><form method="post" data-optional-comment="true"><?= csrf_field() ?><input type="hidden" name="action" value="reject_withdrawal"><input type="hidden" name="id" value="<?= (int)$w['id'] ?>"><input type="hidden" name="admin_comment"><button class="button small danger" type="submit">Отклонить</button></form></td></tr><?php endforeach; ?></tbody></table></div></section><?php endif; ?>
<?php if ($tab === 'stats'): ?><section class="stats-grid"><article class="stat-card"><span>Рекрутеров</span><strong><?= $stats['recruiters'] ?></strong></article><article class="stat-card"><span>Курьеров</span><strong><?= $stats['couriers'] ?></strong></article><article class="stat-card"><span>Активных заказов</span><strong><?= $stats['orders'] ?></strong></article><article class="stat-card"><span>Выплачено</span><strong><?= format_money($stats['paid']) ?></strong></article></section><?php endif; ?>
<?php if ($tab === 'recruiters'): ?><section class="panel"><div class="panel-heading"><h2>Рекрутеры</h2></div><div class="table-wrap"><table class="data-table wide-table"><thead><tr><th>Имя</th><th>Email</th><th>Код</th><th>Инд. ставка</th><th>Действия</th></tr></thead><tbody><?php foreach ($recruiters as $r): ?><tr><form method="post"><?= csrf_field() ?><input type="hidden" name="action" value="save_recruiter"><input type="hidden" name="id" value="<?= (int)$r['id'] ?>"><td><input name="full_name" value="<?= e($r['full_name']) ?>" required></td><td><input type="email" name="email" value="<?= e($r['email']) ?>" required></td><td><code><?= e($r['referral_code']) ?></code></td><td><input type="number" name="custom_reward" min="0" placeholder="Глоб./город" value="<?= e($r['custom_reward']) ?>"></td><td class="actions-cell"><button class="button small" type="submit">Сохранить</button></form><form method="post" data-confirm="Удалить рекрутера?"><?= csrf_field() ?><input type="hidden" name="action" value="delete_recruiter"><input type="hidden" name="id" value="<?= (int)$r['id'] ?>"><button class="button small danger" type="submit">Удалить</button></form></td></tr><?php endforeach; ?></tbody></table></div></section><?php endif; ?>
<?php if ($tab === 'couriers'): ?><section class="panel"><div class="panel-heading"><h2>Курьеры</h2><form><input type="hidden" name="tab" value="couriers"><select name="status" onchange="this.form.submit()"><option value="">Все статусы</option><?php foreach (array('pending','active','rejected','paused','blocked') as $s): ?><option value="<?= e($s) ?>" <?= $statusFilter===$s?'selected':'' ?>><?= e(status_label($s)) ?></option><?php endforeach; ?></select></form></div><div class="table-wrap"><table class="data-table wide-table"><thead><tr><th>Рекрутер</th><th>Имя</th><th>Город</th><th>Тип</th><th>Телефон</th><th>Статус</th><th>Причина</th><th>Заказы</th><th>Действия</th></tr></thead><tbody><?php foreach ($couriers as $c): ?><tr><form method="post"><?= csrf_field() ?><input type="hidden" name="action" value="save_courier"><input type="hidden" name="id" value="<?= (int)$c['id'] ?>"><td><?= e($c['recruiter_name']) ?></td><td><input name="first_name" value="<?= e($c['first_name']) ?>"><input name="last_name" value="<?= e($c['last_name']) ?>"></td><td><input name="city" value="<?= e($c['city']) ?>"></td><td><select name="delivery_type"><option value="auto" <?= $c['delivery_type']==='auto'?'selected':'' ?>>Авто</option><option value="foot" <?= $c['delivery_type']==='foot'?'selected':'' ?>>Пешим</option><option value="bike" <?= $c['delivery_type']==='bike'?'selected':'' ?>>Вело</option></select></td><td><input name="phone" value="<?= e($c['phone']) ?>"></td><td><select name="status"><?php foreach (array('pending','active','rejected','paused','blocked') as $s): ?><option value="<?= e($s) ?>" <?= $c['status']===$s?'selected':'' ?>><?= e(status_label($s)) ?></option><?php endforeach; ?></select></td><td><input name="rejection_reason" value="<?= e($c['rejection_reason']) ?>"></td><td><input type="number" min="0" name="orders_count" value="<?= (int)$c['orders_count'] ?>"></td><td class="actions-cell"><button class="button small" type="submit">Сохранить</button></form><form method="post" data-confirm="Удалить курьера?"><?= csrf_field() ?><input type="hidden" name="action" value="delete_courier"><input type="hidden" name="id" value="<?= (int)$c['id'] ?>"><button class="button small danger" type="submit">Удалить</button></form></td></tr><?php endforeach; ?></tbody></table></div></section><?php endif; ?>
<?php if ($tab === 'city-rates'): ?><section class="panel narrow-panel"><div class="panel-heading"><h2>Добавить ставку</h2></div><div class="panel-body"><form method="post" class="form-card plain-form"><?= csrf_field() ?><input type="hidden" name="action" value="save_city_rate"><label>Город<input name="city" required></label><label>Ставка за заказ<input type="number" min="0" name="reward_per_order" required></label><button class="button" type="submit">Сохранить</button></form></div></section><section class="panel"><div class="table-wrap"><table class="data-table"><thead><tr><th>Город</th><th>Ставка</th><th></th></tr></thead><tbody><?php foreach ($cityRates as $rate): ?><tr><td><?= e($rate['city']) ?></td><td><?= format_money($rate['reward_per_order']) ?></td><td><form method="post" data-confirm="Удалить ставку?"><?= csrf_field() ?><input type="hidden" name="action" value="delete_city_rate"><input type="hidden" name="id" value="<?= (int)$rate['id'] ?>"><button class="button small danger">Удалить</button></form></td></tr><?php endforeach; ?></tbody></table></div></section><?php endif; ?>
<?php if ($tab === 'news'): ?><section class="panel narrow-panel"><div class="panel-heading"><h2>Опубликовать новость</h2></div><div class="panel-body"><form method="post" class="form-card plain-form"><?= csrf_field() ?><input type="hidden" name="action" value="post_news"><label>Заголовок<input name="title" required></label><label>Текст<textarea name="body" rows="5" required></textarea></label><button class="button" type="submit">Опубликовать</button></form></div></section><section class="panel"><div class="panel-heading"><h2>Последние новости</h2></div><div class="panel-body news-list"><?php foreach ($news as $n): ?><article><h3><?= e($n['title']) ?></h3><p><?= e($n['body']) ?></p><time><?= e(date('d.m.Y H:i', strtotime($n['created_at']))) ?></time></article><?php endforeach; ?></div></section><?php endif; ?>
<?php if ($tab === 'settings'): ?><section class="panel narrow-panel"><div class="panel-heading"><h2>Настройки</h2></div><div class="panel-body"><form method="post" class="form-card plain-form"><?= csrf_field() ?><input type="hidden" name="action" value="save_setting"><label>Глобальная ставка, ₽<input type="number" min="0" name="reward_per_order" value="<?= (int)$reward ?>"></label><label>Минимальная выплата, ₽<input type="number" min="0" name="min_withdrawal" value="<?= (int)$minWithdrawal ?>"></label><button class="button" type="submit">Сохранить</button></form></div></section><?php endif; ?>
<?php require __DIR__ . '/../includes/admin-footer.php'; ?>
